
CREATE TABLE CLIENTES (
    CLIENTE_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    TELEFONE VARCHAR2(15),
    EMAIL VARCHAR2(100),
    ENDERECO VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIENTE_ID),
    CONSTRAINT UNQ_CLIENTES_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PROPRIETARIOS (
    PROPRIETARIO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    TELEFONE VARCHAR2(15),
    EMAIL VARCHAR2(100),
    CONSTRAINT PK_PROPRIETARIOS PRIMARY KEY (PROPRIETARIO_ID),
    CONSTRAINT UNQ_PROPRIETARIOS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PROPRIEDADES (
    PROPRIEDADE_ID NUMBER NOT NULL,
    ENDERECO VARCHAR2(255) NOT NULL,
    TIPO VARCHAR2(50),
    PRECO NUMBER(15,2),
    STATUS VARCHAR2(50) CHECK (STATUS IN ('Disponível', 'Alugada', 'Indisponível')),
    PROPRIETARIO_ID NUMBER NOT NULL,
    CONSTRAINT PK_PROPRIEDADES PRIMARY KEY (PROPRIEDADE_ID),
    CONSTRAINT FK_PROPRIEDADES_PROPRIETARIOS FOREIGN KEY (PROPRIETARIO_ID)
        REFERENCES PROPRIETARIOS (PROPRIETARIO_ID)
        ON DELETE CASCADE
);

CREATE TABLE CONTRATOS (
    CONTRATO_ID NUMBER NOT NULL,
    PROPRIEDADE_ID NUMBER NOT NULL,
    PROPRIETARIO_ID NUMBER NOT NULL,
    CLIENTE_ID NUMBER,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    VALOR_MENSAL NUMBER(10,2) CHECK (VALOR_MENSAL > 0),
    TIPO VARCHAR2(50),
    CONSTRAINT PK_CONTRATOS PRIMARY KEY (CONTRATO_ID),
    CONSTRAINT FK_CONTRATOS_PROPRIEDADES FOREIGN KEY (PROPRIEDADE_ID)
        REFERENCES PROPRIEDADES (PROPRIEDADE_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_CONTRATOS_PROPRIETARIOS FOREIGN KEY (PROPRIETARIO_ID)
        REFERENCES PROPRIETARIOS (PROPRIETARIO_ID),
    CONSTRAINT FK_CONTRATOS_CLIENTES FOREIGN KEY (CLIENTE_ID)
        REFERENCES CLIENTES (CLIENTE_ID)
);

CREATE TABLE MANUTENCOES_PROPRIEDADE (
    MANUTENCAO_ID NUMBER NOT NULL,
    PROPRIEDADE_ID NUMBER NOT NULL,
    DATA_MANUTENCAO DATE NOT NULL,
    DESCRICAO CLOB,
    CUSTO NUMBER(10,2) CHECK (CUSTO >= 0),
    CONSTRAINT PK_MANUTENCOES PRIMARY KEY (MANUTENCAO_ID),
    CONSTRAINT FK_MANUTENCOES_PROPRIEDADES FOREIGN KEY (PROPRIEDADE_ID)
        REFERENCES PROPRIEDADES (PROPRIEDADE_ID)
        ON DELETE CASCADE
);

CREATE INDEX IDX_PROPRIEDADES_STATUS ON PROPRIEDADES (STATUS);
CREATE INDEX IDX_CONTRATOS_DATA_INICIO ON CONTRATOS (DATA_INICIO);
